import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { RULES, RULES_VERSION } from "./config";
import { finger, palm, profile, sigma } from "./evaluator";
import { advanceHold, emptyHold, holdProgress, stableScore, type Hold } from "./scoring";
import type { Evaluation, Phase, TrackingFrame } from "./types";

type Result={name:string;accuracy:number;passed:boolean;reason?:string};
const workerUrl=new URL("./tracking.worker.ts",import.meta.url);
const labels:Record<Phase,string>={landing:"",loading:"Готовим камеру",calibrating:"Проверь положение",ready:"Покажи ладонь",countdown:"Приготовься",sigma:"Sigma",roundResult:"Засчитано",moggerProfile:"Mogger · поворот",moggerFinger:"Mogger · палец",results:"Итоги",paused:"Пауза",recoverableError:"Ошибка"};
const copy={sigma:"Слегка прищурься и опусти брови. Удержи позу.",profile:"Поверни голову в любую сторону до зелёной дуги.",finger:"Сохраняй поворот. Выпрями указательный палец и веди к метке."};
function clamp(n:number){return Math.max(0,Math.min(1,n))}
function Sample({kind}:{kind:"sigma"|"mogger"}){return <div className={`sample ${kind}`} aria-label={kind==="sigma"?"Образец выражения Sigma":"Образец позы Mogger"}><div className="sample-label">ОБРАЗЕЦ</div><svg viewBox="0 0 180 150" role="img"><circle cx="90" cy="76" r="47" fill="none" stroke="currentColor" strokeWidth="5"/><path d={kind==="sigma"?"M58 66 Q70 59 80 66 M100 66 Q110 59 122 66":"M70 65 Q78 57 86 65 M104 65 Q112 57 120 65"} fill="none" stroke="currentColor" strokeWidth="6" strokeLinecap="round"/><path d="M71 98 Q90 106 109 98" fill="none" stroke="currentColor" strokeWidth="5" strokeLinecap="round"/>{kind==="mogger"&&<><path d="M135 100 L154 82 L161 90 L142 109" fill="none" stroke="currentColor" strokeWidth="7" strokeLinecap="round"/><circle cx="134" cy="100" r="7" fill="var(--lime)"/></>}</svg><strong>{kind==="sigma"?"SIGMA":"MOGGER"}</strong></div>}
function Circle({value}:{value:number}){return <div className="hold" style={{"--p":`${value*100}%`} as React.CSSProperties}><span>{Math.round(value*100)}%</span></div>}
export default function App(){
 const video=useRef<HTMLVideoElement>(null), canvas=useRef<HTMLCanvasElement>(null), worker=useRef<Worker|null>(null), stream=useRef<MediaStream|null>(null), latest=useRef<TrackingFrame|undefined>(undefined), session=useRef(0), busy=useRef(false), frameFailures=useRef(0), phaseRef=useRef<Phase>("landing"), hold=useRef<Hold>(emptyHold()), palmHold=useRef<number|null>(null), roundStart=useRef(0), profileSide=useRef(false), timerRef=useRef<number|undefined>(undefined);
 const [phase,setPhase]=useState<Phase>("landing"),[message,setMessage]=useState("Включи камеру, а затем играй без мыши."),[quality,setQuality]=useState(0),[progress,setProgress]=useState(0),[seconds,setSeconds]=useState(0),[results,setResults]=useState<Result[]>([]),[error,setError]=useState(""),[cameraLive,setCameraLive]=useState(false),[debug,setDebug]=useState(location.search.includes("debug=1")),[stats,setStats]=useState({fps:0,age:0,ms:0,yaw:0});
 phaseRef.current=phase;
 const best=useMemo(()=>{try{const x=JSON.parse(localStorage.getItem(`memeface:${RULES_VERSION}`)??"{}");return Number(x.best)||0}catch{return 0}},[]);
 const stop=useCallback(()=>{cancelAnimationFrame(timerRef.current??0);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;worker.current?.postMessage({type:"close"});worker.current?.terminate();worker.current=null;busy.current=false;frameFailures.current=0;setCameraLive(false);},[]);
 useEffect(()=>stop, [stop]);
 const transition=(next:Phase,msg?:string)=>{hold.current=emptyHold();setProgress(0);setQuality(0);phaseRef.current=next;setPhase(next);if(msg)setMessage(msg);};
 const endRound=(name:string,passed:boolean,reason?:string)=>{const accuracy=passed?Math.max(RULES.pass,stableScore(hold.current)):stableScore(hold.current);const result={name,accuracy,passed,reason};setResults(prev=>[...prev,result]);transition(name==="Sigma"?"roundResult":"results",passed?"ЗАСЧИТАНО":"Время вышло"); if(name==="Sigma")setTimeout(()=>transition("moggerProfile",copy.profile),1050);};
 const evaluate=useCallback((frame:TrackingFrame)=>{const p=phaseRef.current; if(!frame.face && !["ready","results"].includes(p)) {setMessage("Лицо не видно — вернись в кадр");setProgress(0);hold.current=emptyHold();return}
  if(p==="ready"||p==="results"){const open=palm(frame.hands); if(open){palmHold.current??=frame.ts;if(frame.ts-palmHold.current>RULES.palmMs){palmHold.current=null; startRun();}} else palmHold.current=null;return;}
  let ev:Evaluation|undefined, name=""; if(p==="sigma"){ev=sigma(frame.face);name="Sigma"} else if(p==="moggerProfile"){ev=profile(frame.face);name="Mogger"} else if(p==="moggerFinger"){ev=finger(frame.face,frame.hands);name="Mogger"} else return;
  const valid=ev.valid && Object.values(ev.gates).every(Boolean); const pass=valid&&ev.quality>=RULES.pass; hold.current=advanceHold(hold.current,pass,ev.quality,frame.ts); const nextProgress=holdProgress(hold.current,frame.ts); setQuality(ev.quality);setProgress(nextProgress);setMessage(pass?"Отлично, удержи":ev.issues[0]?.text??"Собери позу");setStats(s=>({...s,age:performance.now()-frame.ts,ms:frame.duration,yaw:ev?.metrics.yaw??s.yaw}));
  if(p==="moggerProfile"&&valid&&ev.quality>=65){ if(!profileSide.current){profileSide.current=true;setMessage("Поворот готов. Поднеси палец к зелёной метке");transition("moggerFinger",copy.finger);} }
  else if(nextProgress>=1)endRound(name,true);
 },[]);
 const startRun=()=>{setResults([]);profileSide.current=false;transition("countdown","Ладонь принята. Приготовься…");setTimeout(()=>{roundStart.current=performance.now();transition("sigma",copy.sigma)},900)};
 const startCamera=async()=>{stop();setError("");transition("loading","Запрашиваем только видео с фронтальной камеры…");try{if(!navigator.mediaDevices?.getUserMedia)throw new Error("Этот браузер не поддерживает доступ к камере.");const compact=matchMedia("(max-width: 680px)").matches;const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"user"},width:{ideal:compact?640:1280},height:{ideal:compact?480:720}},audio:false});stream.current=s;const v=video.current;if(!v)throw new Error("Не удалось подготовить предпросмотр камеры.");v.srcObject=s;await new Promise<void>((resolve,reject)=>{const timeout=window.setTimeout(()=>reject(new Error("Камера не начала передавать видео.")),5000);v.onloadedmetadata=()=>{clearTimeout(timeout);resolve()};v.onerror=()=>{clearTimeout(timeout);reject(new Error("Браузер не смог открыть поток камеры."))}});await v.play();setCameraLive(true);const w=new Worker(workerUrl,{type:"module"});worker.current=w;const own=++session.current;w.onmessage=(e:MessageEvent<any>)=>{const x=e.data;if(x.session!==session.current)return;if(x.type==="ready"){transition("calibrating","Модели готовы. Смотри в камеру…");setTimeout(()=>transition("ready","Покажи открытую ладонь, чтобы начать"),900)}else if(x.type==="result"){busy.current=false;frameFailures.current=0;latest.current=x;evaluate(x)}else if(x.type==="error"||x.type==="frameError"){busy.current=false;setError(`Распознавание не запустилось: ${x.message}`);transition("recoverableError");stop()}};w.postMessage({type:"init",session:own});renderLoop();}catch(e){stop();const msg=e instanceof DOMException&&e.name==="NotAllowedError"?"Камера запрещена. Разреши её в настройках браузера и повтори.":e instanceof DOMException&&e.name==="NotFoundError"?"Камера не найдена.":e instanceof Error?e.message:"Камера недоступна.";setError(msg);transition("recoverableError");}};
 const renderLoop=()=>{const tick=async()=>{const v=video.current,w=worker.current;if(v&&w&&v.readyState>=2&&!busy.current){try{busy.current=true;const bitmap=await createImageBitmap(v);w.postMessage({type:"frame",bitmap,ts:performance.now(),session:session.current},[bitmap]);}catch{busy.current=false;frameFailures.current+=1;if(frameFailures.current>=2){setError("Браузер не смог передать кадры камеры в распознавание. Попробуй Chrome или перезапусти камеру.");transition("recoverableError");stop();return;}}}draw();const p=phaseRef.current;if(["sigma","moggerProfile","moggerFinger"].includes(p)){const total=p==="sigma"?RULES.sigmaMs:RULES.moggerMs;const elapsed=performance.now()-roundStart.current;setSeconds(Math.max(0,Math.ceil((total-elapsed)/1000)));if(elapsed>total){if(p==="sigma")endRound("Sigma",false,"timeout");else endRound("Mogger",false,"timeout")}}timerRef.current=requestAnimationFrame(tick)};timerRef.current=requestAnimationFrame(tick)};
 const draw=()=>{const v=video.current,c=canvas.current,f=latest.current?.face;if(!v||!c)return;const rect=v.getBoundingClientRect(),dpr=devicePixelRatio;c.width=rect.width*dpr;c.height=rect.height*dpr;c.style.width=`${rect.width}px`;c.style.height=`${rect.height}px`;const x=c.getContext("2d")!;x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,rect.width,rect.height);if(!f)return;x.strokeStyle="#d7ff63";x.lineWidth=2;f.landmarks.slice(0,468).filter((_,i)=>i%9===0).forEach(q=>{x.beginPath();x.arc((1-q.x)*rect.width,q.y*rect.height,2,0,Math.PI*2);x.stroke()});if(phaseRef.current==="moggerFinger"){const m=finger(f,latest.current?.hands).metrics;if(m.targetX){x.fillStyle="#d7ff63";x.beginPath();x.arc((1-m.targetX)*rect.width,m.targetY*rect.height,15,0,Math.PI*2);x.fill();}}};
 useEffect(()=>{const on=()=>{if(document.hidden&&["sigma","moggerProfile","moggerFinger"].includes(phaseRef.current)){transition("paused","Игра на паузе. Вернись к камере и нажми продолжить.")}};document.addEventListener("visibilitychange",on);return()=>document.removeEventListener("visibilitychange",on)},[]);
 const total=results.reduce((a,r)=>a+Math.round(r.accuracy*10),0); const stage=["sigma","moggerProfile","moggerFinger"].includes(phase);
 return <main><header><div className="brand">MEME<span>FACE</span></div><button className="quiet" onClick={()=>setDebug(x=>!x)} aria-label="Переключить отладку">{debug?"debug on":"?"}</button></header><section className={`booth ${phase}`}><div className="camera-wrap"><video ref={video} muted playsInline aria-label="Предпросмотр камеры"/><canvas ref={canvas} aria-hidden="true"/>{stage&&<div className="camera-top"><b>{labels[phase]}</b><span>{seconds} c</span></div>} {stage&&<Circle value={progress}/>}</div><aside className="guide">{(phase==="sigma"||phase==="roundResult")?<Sample kind="sigma"/>:<Sample kind="mogger"/>}<div className="steps"><span className={phase==="moggerProfile"?"active":""}>1. Повернись</span><span className={phase==="moggerFinger"?"active":""}>2. Палец к метке</span><span>3. Удержи</span></div></aside></section><section className="status" aria-live="polite"><div className="badge">{labels[phase]||"ПОПРОБУЙ"}</div><h1>{phase==="landing"?"Повтори мем. Камера подскажет как.":message}</h1>{stage&&<p>Совпадение <b>{quality}%</b> · игровой показатель, не оценка внешности.</p>}{phase==="landing"&&<p>Два челленджа, полминуты, только лицо и руки.</p>}{phase==="landing"&&<button className="primary" onClick={startCamera}>Включить камеру</button>}{phase==="recoverableError"&&<><p className="error">{error}</p><button className="primary" onClick={startCamera}>Попробовать снова</button></>}{phase==="paused"&&<button className="primary" onClick={()=>transition("ready","Покажи ладонь, чтобы начать заново")}>Продолжить</button>}{["ready","results"].includes(phase)&&<p className="palm">🖐 Покажи открытую ладонь · или <button onClick={startRun}>начни кнопкой</button></p>}</section>{phase==="results"&&<section className="results"><h2>Твой мем-отчёт</h2><div className="score">{total}<small>/ 2000</small></div>{results.map(r=><article key={r.name}><b>{r.name}</b><span>{r.passed?"ЗАСЧИТАНО":"ВРЕМЯ ВЫШЛО"}</span><strong>{r.accuracy}%</strong></article>)}<p>Лучший локальный результат: {Math.max(best,total)}. Совет: начинай с устойчивого света и держи лицо в центре.</p><button className="primary" onClick={startRun}>Повторить сейчас</button><button className="quiet stop" onClick={()=>{stop();transition("landing","Камера выключена.")}}>Выключить камеру</button></section>}{debug&&<pre className="debug">age {Math.round(stats.age)}ms · inference {Math.round(stats.ms)}ms · yaw {stats.yaw.toFixed(2)} · phase {phase} · hold {Math.round(progress*RULES.holdMs)}ms</pre>}<footer>Видео обрабатывается на устройстве. Фото не сохраняются.</footer></main>
}
